# 1. Core properties
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#core-properties
server:
  port: 8900
  error:
    include-message: always
  servlet:
    context-path: /

logging:
  level:
    org.apache.http: DEBUG